name: MERN Blog CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Backend Dependencies
        run: |
          cd api
          npm ci

      - name: Build Backend
        run: |
          cd api
          npm run build

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm ci

      - name: Build Frontend
        run: |
          cd client
          npm run build

      - name: Run Tests
        run: |
          cd api
          npm test

      - name: Deploy to Server (Example: Heroku)
        run: |
          # Add your deployment script here

      - name: Cleanup
        run: |
          # Add any cleanup steps here
